# http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
# https://github.com/whoshuu/cpr/blob/master/.travis.yml

language: cpp
sudo: required
dist: xenial
notifications:
  slack: era-tum:H6XLebbfxen7b1oqUO1nNVny

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake-3.2
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - cmake-3.2
            - clang-3.7
      env: COMPILER=clang++-3.7

before_script:
  - export CXX=$COMPILER CC=$CCOMPILER
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..

script:
  - make VERBOSE=1 -j 4
  - ctest --verbose -j 4

notifications:
  email: false
